# Generated by Django 3.2.12 on 2022-09-24 16:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please enter your name', max_length=150)),
                ('last_name', models.CharField(help_text='Please enter your lastname', max_length=150)),
                ('username', models.CharField(default='c9514dfb-308d-4584-84f2-ef0ed4434820', help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('trusted_contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ')),
                ('reason', models.TextField()),
            ],
        ),
    ]
